name: Publish to Qiita

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Publish to Qiita
        run: npx --yes @qiita/qiita-cli@latest publish --all --root .
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
